### ISSUE TITLE
Extraneous logging floods log

### ISSUE THREAD

**Issue by tombriggsallego** [MeltanoLabs/meltano-map-transform#14]
Line 120 of mapper.py is

self.logger.info(stream_map.stream_alias)

This produces a line in the log with the stream name for every record processed by the mapper... which for a stream with lots of records floods the log with useless messages. Can that line be removed? If not can it be made a debug level message so it doesn't appear in the log by default?

Thanks!

**Comment by edgarrmondragon** [comment]
@tombriggsallego thanks for reporting! I think the line can be safely removed as it's a leftover from initial dev work 👍 

Would be up for starting an MR for that?

**Comment by tombriggsallego** [comment]
@edgarrmondragon easy enough!
