### ISSUE TITLE
Version pinning for `meltano-map-transform`

### ISSUE THREAD

**Issue by aaronsteers** [MeltanoLabs/meltano-map-transform#2]
In follow-up to our slack discussion [here](https://meltano.slack.com/archives/CKHP6G5V4/p1642114023056500), I realized the process did not account for matching up the version number in the tag with the version number in `pyproject.toml`. Since the version in `pyproject.toml` is `0.0.1`, I think I will just delete the `v0.1.0` tag and release and recreate as `v0.0.1`.

fyi @edgarrmondragon

**Comment by aaronsteers** [comment]
I'll go ahead and take the immediate next action to recreate the release. Then we can discuss process here for keeping them aligned.

**Comment by aaronsteers** [comment]
Update: I was able to "Edit" the release in the web UI, renaming the release and creating a new tag with the correct version number. Then I deleted the old tag (`v0.1.0`).

The link to the updated release is: https://github.com/MeltanoLabs/meltano-map-transform/releases/tag/v0.0.1

**Comment by edgarrmondragon** [comment]
I've implemented the common version bump from the Meltano org: https://github.com/MeltanoLabs/meltano-map-transform/pull/56
