### ISSUE TITLE
Mapper assumes wrong schema when just whitelisting fields

### ISSUE THREAD

**Issue by JohannesRudolph** [MeltanoLabs/meltano-map-transform#66]
I have this simplified mapping to filter properties from https://github.com/singer-io/tap-pipedrive which unfortunately doesn't support field selection. 

So I came up with this config
```
    mappings: 
    - name: pipedrive-exclude-custom-fields
      config:
        stream_maps:
          activities:
            id: id
            deal_title: deal_title
            __else__: null
```

In the source, `id` is an INT and `deal_title` is a nullable STRING. 

The record messages look about right, but the schema message is wrong, making my `id` a nullable string (instead of INT)
```
2022-10-11T09:14:18.305269Z [info     ] {"type": "RECORD", "stream": "activities", "record": {"id": 4786, "deal_title": null}, "time_extracted": "2022-10-11T09:14:18.303118Z"} cmd_type=elb consumer=True name=meltano-map-transformer producer=True stdio=stdout string_id=meltano-map-transformer

2022-10-11T09:18:28.895510Z [info     ] {"type": "SCHEMA", "stream": "activities", "schema": {"type": "object", "properties": {"id": {"type": ["string", "null"]}, "deal_title": {"type": ["string", "null"]}}}, "key_properties": ["id"]} cmd_type=elb consumer=True name=meltano-map-transformer producer=True stdio=stdout string_id=meltano-map-transformer
```

This causes failures in my loader target, because records don't match the announced schemas. 

Now, I get that [schema detection capabilities are limited](https://sdk.meltano.com/en/latest/stream_maps.html#schema-detection-capabilities-are-limited) but automated schema detection case 2. here https://sdk.meltano.com/en/latest/stream_maps.html#automatic-schema-detection says that the property from the orginial stream should have the same data type. 

I can work around this by explicitly rapping with `int()` but this is super tedious for this simple use case. Also, I have yet to figure out what to do about nullable ints...

Can you make this work with simple schema auto detection?

**Comment by edgarrmondragon** [comment]
@tayloramurphy I can confirm this bug. https://github.com/MeltanoLabs/meltano-map-transform/issues/30 is related.

**Comment by JohannesRudolph** [comment]
Any update here? It would solve a lot of problems for us in dealing with taps that are not well-behaved.

**Comment by edgarrmondragon** [comment]
I think I have a fix for this. For `prop_key: prop_def`, we just need to fall back to the original schema if `prop_def` was present there.

**Comment by tayloramurphy** [comment]
@JohannesRudolph thanks for the ping on this! We had this in our Engineering Board already but it doesn't show up in the sidebar for some reason https://github.com/orgs/meltano/projects/3/views/2
